version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:
  # API GATEWAY
  rc-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway-dev
    volumes:
      - ./:/app
    environment:
      RC_AUTHENTICATION_HOST: rc-authentication
      RC_BACKEND_HOST: rc-backend
      RC_PUBLICATIONS_HOST: rc-publications
      PORT: 80
    ports:
      - 8000:80