version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:
  # API GATEWAY
  rc-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rc-api-gateway
    volumes:
      - ./:/app
    environment:
      RC_AUTHENTICATION_HOST: rc-auth
      RC_BACKEND_HOST: rc-api
      PORT: 80
    ports:
      - 8001:80